# Generated by Django 3.2.9 on 2022-04-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhenToWork', '0003_auto_20220406_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='New Document', max_length=255),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
