# Generated by Django 3.2.9 on 2022-04-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhenToWork', '0005_auto_20220409_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='item',
            field=models.CharField(default='New Item', max_length=200),
        ),
    ]
